### ISSUE TITLE
clean install with mariadb fails on rpi

### ISSUE THREAD

**Issue by mojjj** [haiwen/seafile-rpi#21]
latest raspian lite image
latest mariadb

running ./setup-seafile-mysql.sh 
using manual or creation mode of script 

error is:
Error: Failed to init seahub database: Table '`seahub-db`.`admin_log_adminlog`' already exists

**Comment by jobenvil** [comment]
hi @mojjj I think your issue is not related with software bug, I think even more an installation issue. 

The error "already exists" refers that the script was executed more than one time.

My suggestion: There is an [official support forum from seafile](https://forum.seafile.com/), check it for further help. You should attach the steps that you performed before. Use the CLI history command to check your own steps.

**Comment by mojjj** [comment]
very likely usererror on my side. nvm i would not waste more time hre. using sqlite now on fresh install. closing.

**Comment by ExploWare** [comment]
/me2
I ran the setup-seafile-mysql.sh for the first time and this error popped up., seafile version 6.2.2 on Debian GNU/Linux 9.2 (stretch)

**Comment by jobenvil** [comment]
hi @ExploWare I think your issue is not related with software bug, I think even more an installation issue.

The error "already exists" refers that the script was executed more than one time.

My suggestion: There is an official support forum from seafile, check it for further help. You should attach the steps that you performed before. Use the CLI history command to check your own steps.
