### ISSUE TITLE
Update rpi 6.0.9 to 6.1.1 failed "Internal Server Error"

### ISSUE THREAD

**Issue by Paul75** [haiwen/seafile-rpi#22]
Hello,

I updated to 6.1.1 and not problem launch correctly but when i go to the web I have : "Internal Server Error"

Thanks for help

**Comment by jobenvil** [comment]
dear @Paul75 , let me know:

- your linux distro name and version
- your phyton version like 2.7.12 or 2.7.9, etc
- if you have had phyton-requests installed

after that you have colleted these infos, try this:

`sudo apt-get install python-pip`

We suffered this problem on the past (well known issue, refer to Seafile Forum for more infos) and I try to isolate the root cause in order to improve documentation. Important here to know the situation before and after.

Thank you in advance

**Comment by Paul75** [comment]
Hello,

- My system Ubuntu 16.04.2 LTS
- Python version 2.7.12
- i intalled you line it not intalled....

**Comment by jobenvil** [comment]
thanks, let me know if it worked. Reset pls the server.

**Comment by Paul75** [comment]
I resart server and nothing.

(only have stop and start seafile and seahub)

**Comment by jobenvil** [comment]
it is installed `python-requests` module?
**Edit:** Check with `pip list --format=columns`

**Comment by Paul75** [comment]
not installed, I installed and solve issue ....

**Comment by jobenvil** [comment]
> I installed and solve issue ....

Was the problem solved?

**Comment by Paul75** [comment]
yes solved.

That means the documentation not enouth ?

**Comment by jobenvil** [comment]
Hi, great input! thanks. Yes, this should be officially documented: Need to install "`python-requests`" module. You install `pyhton-requests` with `pip` or `pip2` installer?

**Comment by Paul75** [comment]
I've installed with apt-get install pyhton-requests

**Comment by jobenvil** [comment]
perfect! thanks again
