### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.9.1) or chardet (3.0.4) doesn't match a supported version!

### ISSUE THREAD

**Issue by jhonny-oliveira** [haiwen/seafile-rpi#30]
The latest version of "python-chardet" available in Raspbian (jessie) is 2.3.0-1, thus, not meeting the requirement.

As you can see in the attached file, both the migration script and the seahub daemon are affected by this.

Any ideas on how to sort this out?
[rpi02-seafile_6.3.1_error.log](https://github.com/haiwen/seafile-rpi/files/2181626/rpi02-seafile_6.3.1_error.log)

**Comment by jobenvil** [comment]
Problem is caused by olded `urllib3`  version not from chardet. Update your urlib modules to work with `chardet 3.0.4`

These are my thirdpart modules:

```
root@hiperborea /home/seafile/seafile-server-latest/seahub/thirdpart # cat easy-install.pth
./chardet-3.0.4-py2.7.egg             ####   you can see 3.0.4!
./Django-1.11.13-py2.7.egg
./django_compressor-2.2-py2.7.egg
./django_formtools-2.1-py2.7.egg
./django_post_office-3.0.4-py2.7.egg
./djangorestframework-3.8.2-py2.7.egg
./django_simple_captcha-0.5.7-py2.7.egg
./django_statici18n-1.8.0-py2.7.egg
./gunicorn-19.8.1-py2.7.egg
./python_memcached-1.59-py2.7.egg
./pytz-2018.4-py2.7.egg
./qrcode-5.3-py2.7.egg
./requests-2.18.4-py2.7.egg
./requests_oauthlib-0.8.0-py2.7.egg
./six-1.11.0-py2.7.egg
./openpyxl-2.5.3-py2.7.egg
./django_webpack_loader-0.6.0-py2.7.egg
./setuptools-39.2.0-py2.7.egg
./jsonfield-2.0.2-py2.7.egg
./django_appconf-1.0.2-py2.7.egg
./et_xmlfile-1.0.1-py2.7.egg
./certifi-2018.4.16-py2.7.egg
./oauthlib-2.1.0-py2.7.egg
./django_ranged_response-0.2.0-py2.7.egg
./django_constance-2.1.0-py2.7.egg
./flup-1.0.2-py2.7.egg
./python_dateutil-2.7.3-py2.7.egg
./idna-2.6-py2.7.egg
./rcssmin-1.0.6-py2.7-linux-armv6l.egg
./rjsmin-1.0.12-py2.7-linux-armv6l.egg
./olefile-0.45.1-py2.7.egg
./jdcal-1.4-py2.7.egg
./django_picklefield-1.0.0-py2.7.egg
./captcha-0.2.4-py2.7.egg

```

**Comment by jhonny-oliveira** [comment]
This is what I have on the system:

root@rpi02:~# apt show python-urllib3
Package: python-urllib3
Version: 1.9.1-3
Installed-Size: 245 kB

What do you mean with "Update your urlib modules to work with chardet 3.0.4"?

**Comment by jobenvil** [comment]
yes unfortunately is too old and can not meet the dependencies from chardet, update urllib. 

Here is your solution:
https://forum.seafile.com/t/upgrade-from-6-2-5-to-6-3-1-importerror-cannot-import-name-dependencywarning/6554/4

Check that link on the forum and please refer to the forum in the future because since this realease i will not support anymore GitHub issues. The Seafile Forum is more appropriated and the community will help you there as well. Some issues that you observed here were faced with the x64 version. Therefore is a good start to check firstly the forum in which I'm announcing the new releases:

You can [get it from the Seafile download section](https://www.seafile.com/en/download/).

We **warmly** recommend you first, before to proceed with the update, to take a view to the [Seafile ChangeLog](https://manual.seafile.com/changelog/server-changelog.html), because the requirements had changed considerably in the last releases :nerd_face:

:pushpin: Please remember:

- Don't forget to **stop Seafile Server** before the upgrade (i.e: `service seafile-server stop` or, another example: `service seahub stop && service seafile stop`)
- Don't forget to change the **directory rights** of Seafile after unpacking it (i.e: `chown -R seafile:nogroup seafile-server-6.3.1` or, another example: `sudo chown -R seafile:seafile seafile-server-6.3.1` )
- Don't forget to apply the **upgrade script/s** according your start release && **with** the **properly user** which **in normal case should be seafile** (i.e change to seafile user: `su seafile -s /bin/bash` or, another example: `sudo su seafile`)

[Link](https://forum.seafile.com/t/seafile-server-6-3-is-ready-for-testing-a-wysiwyg-markdown-editor-and-more/6250) to the official announcement in forum. ### **Could be a help regarding known errors in x64 version.**

Once again, thanks to the [developers](https://github.com/haiwen) and Seafile Community

have fun :blush:

**Comment by jhonny-oliveira** [comment]
That was it!

The upgrade was already done, this was an after the fact issue. :)
Next time, I will ask for help in the forum, as you indicated.

Thanks again!
