### ISSUE TITLE
seahub failed to start ()

### ISSUE THREAD

**Issue by PDiracDelta** [haiwen/seafile-rpi#34]
I'm doing a fresh seafile install. The seafile-server runs without issues, but when starting seahub
`sudo systemctl start seahub`
I get the following error:

> Error:Seahub failed to start.
> Please try to run "./seahub.sh start" again

I read online that you get more info when doing:
`sudo ./seahub.sh start-fastcgi`
And this tells me:

> django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

However, in the seafile-server-6.3.4/seahub/seahub/settings.py file, the SECRET_KEY is set.

Update: this has to do with permissions. After some point, I had to 
`chmown seafile:nogroup seafile/*`
because otherwise the seafile service was not able to find ccnet/seafile.ini, but after doing that this weird error about SECRET_KEY started showing up.

**Comment by klangborste** [comment]
What says `journalctl -u seahub` ?
We need logfiles and error messages. Whats the output in seahub.log, seafile.log, ccnet.log, controller.log?

**Comment by PDiracDelta** [comment]
journalctl said nothing, just this:

> feb 21 11:53:12 raspberrypi systemd[1]: Starting Seafile Seahub...
> feb 21 11:53:12 raspberrypi seahub.sh[24062]: LC_ALL is not set in ENV, set to en_US.UTF-8
> feb 21 11:53:12 raspberrypi seahub.sh[24062]: /opt/seafile/seafile-server-latest/seahub.sh: regel 207: waarschuwing: setlocale(): LC_ALL: kan niet van taalregio veranderen (en_US.UTF-8): Bestand of map bestaat n
> feb 21 11:53:12 raspberrypi seahub.sh[24062]: Starting seahub at port 8000 ...
> feb 21 11:53:20 raspberrypi systemd[1]: seahub.service: Main process exited, code=exited, status=1/FAILURE
> feb 21 11:53:20 raspberrypi systemd[1]: Failed to start Seafile Seahub.
> feb 21 11:53:20 raspberrypi systemd[1]: seahub.service: Unit entered failed state.
> feb 21 11:53:20 raspberrypi systemd[1]: seahub.service: Failed with result 'exit-code'.

The log files were empty too (only the error above was in there) but they have been overwritten now so I can't prove it, sorry. I did not check ccnet.log and controller.log, however. Currently everything is working, but I had to install seafile+seahub as the root user, and run it as root user, which is not desirable. This does confirm my suspicion that something is up with file permissions/ownership, I suppose.

By the way: **what is the recommended way to install seafile? As which user?** I cannot find anything about this in the manual, but if I were to install it as the user 'pi', then I run into the "not able to find ccnet/seafile.ini" issue I mentioned.

**Comment by klangborste** [comment]
You don't have to run the service as root. I know now the reason for your problem. You just running the service all the time as root, so also all files which needs to be read and written needs root read/write permisson. I run seahub and seafile as a SystemD service like described here:
https://manual.seafile.com/deploy/start_seafile_at_system_bootup.html

I create one service user for seafile and seahub
`useradd -r -M -s /usr/sbin/nologin seafile`

I followed the suggestions from the site to create "seahub.service" and "seafile.service" unit files.
After that i refresh the configuration and enable the unit files in my targets (in the past called runlevel). So that the services run automatically when my system is starting.
`systemctl daemon-reload`
`systemctl enable seafile.service`
`systemctl enable seahub.service`

Then you can stop your old running seafile/seahub service by killing it or stop it like you did before.

And then set the owner and group permissions
`chown -R seafile:seafile /opt/seafile/`

Finally start the services with SystemD like:
`systemctl start seafile.service`
`systemctl start seahub.service`

**Comment by jobenvil** [comment]
Closing the issue due to inactivity, thanks @klangborste for your contribution.
