### ISSUE TITLE
7.1.4安装失败，缺少seaf-server-init

### ISSUE THREAD

**Issue by Qeynos** [haiwen/seafile-rpi#57]
7.0.5可以正常安装使用，但安装7.1.4时报错"./setup-seafile.sh: line 485: /srv/haiwen/seafile-server-7.1.4/seafile/bin/seaf-server-init: No such file or directory"
缺失的文件在7.0.5安装包中是有的

另外是否可以提供aarch64的安装包，rpi4b有4g内存，64位系统已经很普遍了

**Comment by jobenvil** [comment]
@Qeynos if you have the possibility, check the [forum](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/11945/40). There is the solution.

**Comment by Qeynos** [comment]
> @Qeynos if you have the possibility, check the [forum](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/11945/40). There is the solution.

my python version is 3.6.9,but i use ubuntu-server arm64,and install libc6:armhf,i can start seafile-pi 7.0.5 as well

so do you have any plan to support aarch64 install-pack

**Comment by jobenvil** [comment]
I'm only producing packages for 32bit, since I don't have any possibility to test on 64bit arch. 

But you can compile the seafile server yourself since we have a [build script ](https://github.com/haiwen/seafile-rpi)for that. It take less than an hour and you get the same package than for 32bit.

**Comment by Qeynos** [comment]
i will try to compile ,thanks for your help

**Comment by jobenvil** [comment]
great! don't hesitate to contact me for rising issues.

**Comment by Qeynos** [comment]
> great! don't hesitate to contact me for rising issues.

i compile with "./build3.sh 7.1.4", the pack is seafile-server_7.1.4_i386.tar.gz , but the directory in "$INSTALLDIR/seafile/lib/" is "python2.7", and even ln -s 2.7 to 3.6, still show the error "./setup-seafile.sh: line 485: /srv/haiwen/seafile-server-7.1.4/seafile/bin/seaf-server-init: No such file or directory"

**Comment by jobenvil** [comment]
Hi, the problem is [reported here](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/11945/63) as well and just [fixed](https://github.com/haiwen/seafile-rpi/commit/14264e7c8897c2bb06578c9237eb0e91bc12b4f7#diff-25f23011ca22fd72092923c73cbdb694) here. Ensure that you delete the content of `BUILDFOLDER=haiwen-build` before to run the script and ensure that your system recognices `python -V` >= 3.6 .For Compiling Python 2.7 is not enough. You system must have at least python 3.6.*. Good luck :-)

**Comment by Qeynos** [comment]
i recompile succeed, my os default python is 2.7, so i ln it to python3.6m instead, everything went fine, thanks
