### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by Reen90** [haiwen/seafile-rpi#76]
Hello, 

how is seafile-rpi licensed?
Can someone please provide me the license information?
The only related information the license information on seafile-server. (https://github.com/haiwen/seafile-server/blob/master/LICENSE.txt)

Does the same license apply here?

Best regards

**Comment by luis-andres** [comment]
Hey,

Wondering the same thing here! Is there any update on the matter?

Thanks in advance!

Best

**Comment by jobenvil** [comment]
@luis-andres @Reen90 no idea of that, but I can assume that it is analogue to seafile-server x64 (your link to https://github.com/haiwen/seafile-server/blob/master/LICENSE.txt). Same should apply here. A question? Why is this matter so important?

@freeplant @lins05 Please correct my words if I'm wrong.

**Comment by Reen90** [comment]
@jobenvil It is important since as a developer you need to know under which conditions this software/code can be used.

It is a risk not to know about those conditions and this might lead to considering other options.

**Comment by jobenvil** [comment]
@Rotzbua why should I be aware of the license type? If you are disappointed with my answer/questions, go and ask the devs by yourself. Good luck. @killing @freeplant 

@Reen90  fair enough, thanks. The Seafile software licenses are well defined [here](https://github.com/haiwen/seafile), therefore I asumme that for ARM the same aplies, since it is just the same software, compiled for another architecure more.

**Comment by Gustl22** [comment]
Personally I always prefer the [MIT license](https://opensource.org/licenses/MIT), but I think we can't apply it to this repo, as it has no restrictions whatsoever and existing licenses can't be "downgraded". See [here](https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l)

So then an option would be the [Apache v2 License](https://www.apache.org/licenses/LICENSE-2.0) which is also used by some seafile repos. But I think it is still [INCOMPATIBLE](https://www.apache.org/licenses/GPL-compatibility.html) to the [AFFERO GPL License](https://www.gnu.org/licenses/agpl-3.0.en.html) which is a GPLv3 License and is used by [seafile-server](https://github.com/haiwen/seafile-server/blob/master/LICENSE.txt). But I'm not 100% sure with that, as it is no derivate, but a software using the GPLv3 licensed library in a way.

As last option would be to apply the same license as the [seafile-server](https://github.com/haiwen/seafile-server/blob/master/LICENSE.txt), which I'm not a huge fan of, but at least it would work so that all participants can live with.

@freeplant @lins05 @jobenvil  Do you agree with copying the seafile-server license?
